-- アクセスキー管理テーブル
CREATE TABLE IF NOT EXISTS access_keys (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    access_key VARCHAR(255) NOT NULL UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
